import { RadiantClass } from "./radiant_class";

const geralt = new RadiantClass({
    id: 1,
    name: 'Геральт',
    kind: 'Ведьмак',
    state: 'Жив',
    fullHealth: 250,
    health: 250,
    weapon: 'Серебро',
    minDamage: 40,
    maxDamage: 50,
    buff: 0,
    RangeAttackName: 'Хамум',
    RACount: 2,
    abillity: 'Игни',
    abillityInfo: 'Сожги противника дотла',
    sickAbillity: 'Масло',
    sickInfo: 'Облей маслом меч, монстру будет очень больно',
    fullMana: 80,
    mana: 80,

    healItem: 'Ласточка',
    healCount: 1,
    manaItem: 'Зелье Маны',
    manaCount: 1,
    flyWeapon: 'Арбалет',
    flyCount: 3,
    buffItem: 'Кошка',
    buffItemCount: 2,
    alert: ''

})
const leo = new RadiantClass({
    id: 2,
    name: 'Леонардо',
    kind: 'Черепашка-Ниндзя',
    state: 'Жив',
    fullHealth: 350,
    health: 350,
    weapon: 'Два меча',
    minDamage: 35,
    maxDamage: 50,
    buff: 0,
    RangeAttackName: 'Бросок Меча',
    RACount: 2,
    abillity: 'Скейт',
    abillityInfo: 'Почему не встать на скейт и ударить посильнее?',
    sickAbillity: 'Насмешка',
    sickInfo: 'А жаренных гвоздей не хорчешь?',
    fullMana: 70,
    mana: 70,

    healItem: 'Пицца',
    healCount: 2,
    manaItem: 'Другая пицца',
    manaCount: 1,
    flyWeapon: 'Сюрикен',
    flyCount: 3,
    buffItem: 'Ещё пицца',
    buffItemCount: 2,
    alert: ''

})
const scorpion = new RadiantClass({
    id: 3,
    name: 'Скорпион',
    kind: 'Ниндзя',
    state: 'Жив',
    fullHealth: 300,
    health: 300,
    weapon: 'Крюк',
    minDamage: 30,
    maxDamage: 45,
    buff: 0,
    RangeAttackName: 'Бросок крюка',
    RACount: 2,
    abillity: 'Захват Крюком',
    abillityInfo: 'Лиши противника возможности двигаться и нанеси удар!',
    sickAbillity: 'Ожог',
    sickInfo: 'Пламя изо рта, пока монстр тушит себя, он слаб',
    fullMana: 100,
    mana: 100,

    healItem: 'Огонь',
    healCount: 1,
    manaItem: 'Тоже огонь',
    manaCount: 1,
    flyWeapon: 'Кортик',
    flyCount: 2,
    buffItem: 'Портал',
    buffItemCount: 1,
    alert: ''

})
const hulk = new RadiantClass({
    id: 4,
    name: 'Халк',
    kind: 'Мутант',
    state: 'Жив',
    fullHealth: 500,
    health: 500,
    weapon: 'Кулак',
    minDamage: 60,
    maxDamage: 80,
    buff: 0,
    RangeAttackName: 'Бросок Камня',
    RACount: 3,
    abillity: 'Удар по земле',
    abillityInfo: 'Вся сила Халка уходит в землю!',
    sickAbillity: 'Рёв',
    sickInfo: 'Вопль Халка способен оглушить даже его самого',
    fullMana: 100,
    mana: 100,

    healItem: 'Мясо',
    healCount: 1,
    manaItem: 'Пиво',
    manaCount: 1,
    flyWeapon: 'Камни',
    flyCount: 2,
    buffItem: 'Сила земли',
    buffItemCount: 2,
    alert: ''

})

const flash = new RadiantClass({
    id: 5,
    name: 'Флеш',
    kind: 'Супергерой',
    state: 'Жив',
    fullHealth: 250,
    health: 250,
    weapon: 'Скорость',
    minDamage: 45,
    maxDamage: 60,
    buff: 0,
    RangeAttackName: 'Молния',
    RACount: 2,
    abillity: 'Раздвоение',
    abillityInfo: 'Раздвоение Флеша и нанесение двх ударов',
    sickAbillity: 'Хоровод',
    sickInfo: 'Закрути монстра, чтоб он не понимал где он',
    fullMana: 50,
    mana: 50,

    healItem: 'Вибро',
    healCount: 1,
    manaItem: 'Передых',
    manaCount: 1,
    flyWeapon: 'Ветер',
    flyCount: 3,
    buffItem: 'Заряд',
    buffItemCount: 2,
    alert: ''

})
export {geralt, leo, hulk, scorpion, flash}